# openapi2-functions.yaml
swagger: '2.0'
info:
  title: place-order 
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /place-order:
    post:
      summary: place order
      operationId: place-order
      x-google-backend:
        address: https://us-central1-ultra-mediator-352903.cloudfunctions.net/place-order
      responses:
        '200':
          description: A successful response
          schema:
            type: string