service: aws
frameworkVersion: "3"

provider:
    name: aws
    runtime: nodejs14.x
    region: ca-central-1

functions:
    api:
        handler: handler.handler
        events:
            - httpApi: "*"
