swagger: "2.0"
info:
    title: service-customer-api-gateway
    description: Sample API on API Gateway with a Google Cloud Functions backend
    version: 1.0.0
schemes:
    - https
produces:
    - application/json
paths:
    /api:
        get:
            summary: service-customer-api-gateway
            operationId: service-customer-api-gateway
            x-google-backend:
                address: https://us-central1-serverless-project-356317.cloudfunctions.net/api
            responses:
                "200":
                    description: A successful response
                    schema:
                        type: string
